[platformio]
src_dir = src
include_dir = include

[env:seeed_xiao_esp32s3]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
upload_command = $PYTHONEXE -m esptool --chip esp32s3 --port $UPLOAD_PORT --baud $UPLOAD_SPEED --before default-reset --after hard-reset write-flash -z 0x0 $BUILD_DIR/bootloader.bin 0x8000 $BUILD_DIR/partitions.bin 0xe000 $PROJECT_PACKAGES_DIR/framework-arduinoespressif32/tools/partitions/boot_app0.bin 0x10000 $BUILD_DIR/firmware.bin
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
lib_deps =
    gilmaimon/ArduinoWebsockets @ ^0.5.4
